realworldocaml/book

examples/code/variants/blang.topscript
By stopping using List.mem, which requires the use of polymorphic compare.
=> fixed and accepted corrections

examples/code/gadts/main.topscript
There were a number of small changes, but the primary issue was the misfiring of a warning in Core_kernel. For reasons I don't yet understand, it was resolved by switching to Base. I think we're not yet compiling with safe-string fully on, and doing that will probably fix another problem here, which is that short-paths reports string where bytes is really desired.
=> Fix gadt topscript

book/install.html
I ran into two issues while setting up Vim.  All Merlin commands would return "Not an editor command", and ocp-indent would throw errors when opening Vim, saying `the file substitute(system('opam config var share'), '\n$', '', '''') . "/typerex/ocp-indent/ocp-indent.vim" can not be opened`.
Greping through ~/.opam found the updated paths.  Appending the new ocp-indent path to Vim's run time path got it working.
=> Update paths for vim configuration

bin/bin/gen_jbuild.ml, examples/code/async/jbuild.inc, examples/code/classes/jbuild.inc, examples/code/command-line-parsing/jbuild.inc, examples/code/error-handling/jbuild.inc, examples/code/fcm/jbuild.inc, examples/code/ffi/jbuild.inc, examples/code/files-modules-and-programs/jbuild.inc, examples/code/front-end/jbuild.inc, examples/code/functors/jbuild.inc, examples/code/gadts/jbuild.inc, examples/code/gc/jbuild.inc, examples/code/guided-tour/jbuild.inc, examples/code/imperative-programming/jbuild.inc, examples/code/json/jbuild.inc, examples/code/lists-and-patterns/jbuild.inc, examples/code/maps-and-hash-tables/jbuild.inc, examples/code/memory-repr/jbuild.inc, examples/code/objects/jbuild.inc, examples/code/records/jbuild.inc, examples/code/sexpr/jbuild.inc, examples/code/variables-and-functions/jbuild.inc, examples/code/variants/jbuild.inc
(This is based on top of #2855, #2856 and #2857).
The interesting commit here is fccb947 which replaces stamp files with a `code` alias.  9ff150d shows the difference in the auto-generated files, after running `make dep`.
=> Remove stamp files

Dockerfile, examples/code/files-modules-and-programs/freq-obuild/test.sh, scripts/build
Start by installing everything before copying the source tree: this
way the dependencies can be cached and do not have to be reinstalled
everytime a source file is changed.
=> optimize the Dockerfile

bin/lib/rwo_scripts.ml
This was removed by error in #2858. As there is no `jbuild.sexp` files anymore, the filtering is now done directly on the jbuild files.
=> Restore noise filtering from jbuild files

examples/code/files-modules-and-programs/freq-obuild/freq.sh
Now that the shell script is not run by the CI, it should not be
a problem anymore.
=> Re-enable freq-obuild example

examples/code/records/main2.mlt
Non-deterministic value needs to be propagated manually.
=> Fix record example

book/13-maps-and-hashtables.html, examples/code/fcm/query_handler.mlt, examples/code/files-modules-and-programs/freq-fast/counter.ml, examples/code/maps-and-hash-tables/core_phys_equal.mlt, examples/code/maps-and-hash-tables/main.mlt, examples/code/maps-and-hash-tables/map_vs_hash/jbuild, examples/code/maps-and-hash-tables/map_vs_hash/map_vs_hash.ml, examples/code/maps-and-hash-tables/map_vs_hash2/map_vs_hash2.ml
This is a pretty big rewrite, and reading the diff on github isn't easy, especially because the text and the mlt code aren't together in one file. If you want to read it over, probably the easiest way is to generate the HTML and read it.
There's more I should maybe add in a followup patch, including a section describing how to use Map.M(Int).t and why it's useful.
Also, there's an unrelated fix to an example in the first-class-module section where a section was marked as non-deterministic. This was getting in the way of the build.
=> Base in maps v2

static/jbuild.inc
It seems that the file is not included anymore in the book.
=> Remove unused file in static/jbuild.inc

bin/bin/gen_jbuild.ml, examples/code/async/jbuild.inc, examples/code/classes/jbuild.inc, examples/code/command-line-parsing/jbuild.inc, examples/code/error-handling/jbuild.inc, examples/code/fcm/jbuild.inc, examples/code/ffi/jbuild.inc, examples/code/files-modules-and-programs/jbuild.inc, examples/code/front-end/jbuild.inc, examples/code/functors/jbuild.inc, examples/code/gadts/jbuild.inc, examples/code/gc/jbuild.inc, examples/code/guided-tour/jbuild.inc, examples/code/imperative-programming/jbuild.inc, examples/code/json/jbuild.deps, examples/code/json/jbuild.inc, examples/code/lists-and-patterns/jbuild.inc, examples/code/maps-and-hash-tables/jbuild.inc, examples/code/memory-repr/jbuild.inc, examples/code/objects/jbuild.inc, examples/code/records/jbuild.inc, examples/code/sexpr/jbuild.deps, examples/code/sexpr/jbuild.inc, examples/code/variables-and-functions/jbuild.inc, examples/code/variants/jbuild.inc
.mlt files now implicitely depends on all files in the same directory and
its subdirectories.
=> Remove jbuild.deps files

bin/lib/rwo_book.ml, bin/lib/rwo_html.ml, bin/lib/rwo_html.mli, bin/lib/rwo_toc.ml, book/00-prologue.html, book/01-guided-tour.html, book/02-variables-and-functions.html, book/03-lists-and-patterns.html, book/04-files-modules-and-programs.html, book/05-records.html, book/06-variants.html, book/07-error-handling.html, book/08-imperative-programming.html, book/09-functors.html, book/10-first-class-modules.html, book/11-objects.html, book/12-classes.html, book/13-maps-and-hashtables.html, book/14-command-line-parsing.html, book/15-json.html, book/16-parsing-with-ocamllex-and-menhir.html, book/17-data-serialization.html, book/18-concurrent-programming.html, book/19-foreign-function-interface.html, book/20-runtime-memory-layout.html, book/21-garbage-collector.html, book/22-compiler-frontend.html, book/23-compiler-backend.html
Remove `<html>` and `<body>` tags from the HTML docs. The goal is to get something simple and consistent that we can then parse and translate to markdown without loosing contents and structure.
=> Simplify HTML structure

bin/lib/rwo_index.ml, book/19-foreign-function-interface.html, html2md/jbuild, html2md/main.ml
- trim paragraphs to remove useless spaces
- shorter syntax for idx tags
- add a `--all` options to convert all chapters in one go
- fix renumbering of section headers
=> html2md improvements

bin/lib/expect.ml, bin/lib/expect.mli, bin/lib/scripts.ml
=> Fix broken syntax highlighting caused by empty shell scripts

static/css/app.css
Fix #2880
The new rendering:
That commit also change the font size of "note" boxes to be the same as the "sidebar" and "warning" ones. I still have no idea what the sidebar boxes are about, and why they are treated differently (e.g. they are in a `<aside>` tag instead of a `<div>`) :-) We could probably improve all of that by treating all these boxes almost the same. Just let me know what you prefer.
=> css: fix display of warning boxes

book/install.html, static/css/app.css
I have trying to reduce a bit the empty spaces in the current style and to reduce the visual noise of having so many different font sizes. It's not perfect, but I feel it's a bit better compared to what it was before. There are still two many different fonts, size, and noise to my taste, but the current CSS is complex enough and my time is limited ...
Before:
After:
On the variant chapter (where there are subsections):
Before:
After:
=> Compact style

book/variables-and-functions.md
This is in the section on left-associativity of `|>`. The code snippet above refers to `List.dedup_and_sort` but the text calls it as `List.dedup`.
=> [Variables and Functions] replace List.dedup with List.dedup_and_sort

book/variants.md
In paragraph describing use of the `>` in polymorphic types, the example I think should cite ``[> `Float of float | `Int of int]`` not ``[> `Int of string | `Float of float]``.
=> Fixing polymorphic `>`example in variants.md

book/guided-tour.md
:wave: Thanks for working on this in the open! I'm just starting to learn, and it's been a great resource.
Line 943 calls the native executable `sum.exe`, while 947 calls it `sum.native`, so I updated the latter to make them consistent.
=> Make native executable extension consistent

book/maps-and-hashtables.md
Discussion: https://discuss.ocaml.org/t/possible-typo-base-or-core/2650
=> Fix typo in Hash Tables, "Base" instead of "Core"

static/css/app.css
Previously, the clickable portion of the ToC and Navbar links was the entire horizontal width of their container instead of just the part of the link that has visible text.  While browsing the book, I mis-clicked a few times on what I thought was empty space, but was actually the continuation of a link.
`display: table-cell` is a great replacement for `display: block` because it keeps all the vertical layout the same, while also having a traditional "span style" horizontal fill.
=> Reduce horizontal coverage for clickable area in links

static/css/app.css
When there isn't enough screen real-estate to see the whole navbar at once, a scroll-bar will pop up.  But until then, the scroll-bar is hidden.
=> Change overflow-y on the navigation column to be auto instead of scroll

book/json.md
Duplicate usage of part="generate json".
Change the first one to part="generate types".
=> Fix typo in json.md

book/files-modules-and-programs/README.md, examples/code/files-modules-and-programs/freq-median/counter.ml
> For example, imagine we wanted to add a function to `Counter` for returning
> the line with the median frequency count. If the number of lines is even,
> then there is no precise median, and the function would return the lines
> before and after the median instead. We'll use a custom type to represent the
> fact that there are two possible return values. Here's a possible
> implementation:
> 
> ```ocaml file=../../examples/code/files-modules-and-programs/freq-median/counter.ml,part=1
> type median = | Median of string
>               | Before_and_after of string * string
> 
> let median t =
>   let sorted_strings = 
>     List.sort (Map.to_alist t)
>       ~cmp:(fun (_,x) (_,y) -> Int.descending x y)
>   in
>   let len = List.length sorted_strings in
>   if len = 0 then failwith …
```
=> files-modules-and-programs: List.sort ~cmp should be ~compare

book/concurrent-programming/README.md
String.uppercase has been deprecated. Replacing "String.uppercase" with "String.uppercase_ascii" in Deferred.bind example early in README.md of "Concurrent Programming with Async" chapter that introduces >>= use, as well as two other examples further down.
=> "String.uppercase" --> "String.uppercase_ascii"

examples/code/imperative-programming/dictionary.ml, examples/code/imperative-programming/dictionary.mli
Using orignal polymorphic compare operators in Caml instead of integer compare operators in Base.
Function `find`'s interface is defined as polymorphic in `.mli`.
```ocaml
val find   : ('a, 'b) t -> 'a -> 'b option
```
But `find`'s implement in `.ml` is inferred to `val find : (int, 'a) t -> int -> 'a option`
```ocaml
open Base
let find t key =
List.find_map t.buckets.(hash_bucket key)
~f:(fun (key',data) -> if key' = key then Some data else None)
```
Because the type of the equality operator that’s open in Base is `int -> int -> bool` . So I use the original polymorphic operator in such way:
```ocaml
open Base
let find t key =
List.find_map t.buckets.(hash_bucket key)
~f:(fun (key',data) -> if Caml.(key' = key) then Some data else None)
```
=> Using orignal polymorphic compare operators

book/garbage-collector/README.md
To address https://github.com/realworldocaml/book/issues/3072
=> Fix incorrect link to OCaml manual for runtime - closes #3072

book/functors/README.md
Following the example used to lead to a unhelpful syntax errors from the
compiler.
=> Fix syntax for multiple type constraints on a signature.

book/classes/dune.inc, book/command-line-parsing/dune.inc, book/compiler-backend/dune.inc, book/compiler-frontend/dune.inc, book/concurrent-programming/dune.inc, book/data-serialization/dune.inc, book/error-handling/dune.inc, book/files-modules-and-programs/dune.inc, book/first-class-modules/dune.inc, book/foreign-function-interface/dune.inc, book/functors/dune.inc, book/garbage-collector/dune.inc, book/guided-tour/dune.inc, book/imperative-programming/dune.inc, book/json/dune.inc, book/lists-and-patterns/dune.inc, book/maps-and-hashtables/dune.inc, book/objects/dune.inc, book/parsing-with-ocamllex-and-menhir/dune.inc, book/ppx/dune.inc, book/prologue/dune.inc, book/records/dune.inc, book/runtime-memory-layout/dune.inc, book/variables-and-functions/dune.inc, book/variants/dune.inc, rwo.opam
The binary name for `mdx` changed to `ocaml-mdx` in version `1.3.0`.
We either need to add an upper bound to the `mdx` dependency or to update the `mdx` actions to use the new binary name.
The latter seemed like the right thing to do!
I'm not yet very familiar with those generated `dune` files but expect for `book/ppx/dune.inc` I only trusted the generation process with those changes.
Generating `book/ppx/dune.inc` gave me a totally different file, dropping the `runtest-all` alias entirely and dropping every dependencies and diff actions, except the ones for `x`, being the `README.md` file, in the runtest alias.
I'll investigate this further but if you  have any idea where it might come from I'd gladly take it!
=> Upgrade to mdx >= 1.3.0

book/classes/dune, book/command-line-parsing/dune, book/compiler-backend/dune, book/compiler-frontend/dune, book/concurrent-programming/dune, book/data-serialization/dune, book/error-handling/dune, book/files-modules-and-programs/dune, book/first-class-modules/dune, book/foreign-function-interface/dune, book/functors/dune, book/garbage-collector/dune, book/guided-tour/dune, book/imperative-programming/dune, book/json/dune, book/lists-and-patterns/dune, book/maps-and-hashtables/dune, book/objects/dune, book/parsing-with-ocamllex-and-menhir/dune, book/ppx/dune, book/prologue/dune, book/records/dune, book/runtime-memory-layout/dune, book/variables-and-functions/dune, book/variants/dune
When updating to mdx v1.4.0 I fixed the rules generated by mdx itself but not the handwritten ones so there you go!
=> Update mdx to ocaml-mdx in dune files generation rules

book/files-modules-and-programs/README.md
Because empty code blocks breaks Markdown renders.
Before it was looking like this:
=> Fix syntax highlight in Modules section

book/variables-and-functions/README.md
Depends on #3100, I'm leaving this as draft until it's merged! Note that only the last commit is relevant to this PR.
The tests for this chapter were working but recent `mdx` versions appear to add a trailing whitespace to a toplevel code block evaluation for some reason. The issue has been reported here: https://github.com/realworldocaml/mdx/issues/146
=> Duniverse: Fix Variables and Functions chapter

book/files-modules-and-programs/README.md, examples/code/files-modules-and-programs/freq-median/counter.ml, examples/code/files-modules-and-programs/freq-median/counter.mli, examples/code/files-modules-and-programs/freq-with-counter/counter.ml, examples/code/files-modules-and-programs/freq-with-sig-abstract/counter.ml, examples/code/files-modules-and-programs/freq-with-sig-mismatch/counter.ml, examples/code/files-modules-and-programs/freq-with-sig-mismatch/counter.mli, examples/code/files-modules-and-programs/freq-with-type-mismatch/counter.mli
Depends on #3100, I'm leaving this as draft until it's merged! Note that only the last two commits are relevant to this PR.
This fixes the tests in the "Files, Modules and Programs". Most of the changes were straightforward as it was just out of date error message. There's a few things worth noting though:
- There are trailing whitespaces from the new `mdx` here as well
- `mdx` now adds `;;` after the `[@@@part ...]` attributes, I'm not sure if there's a rationale behind this but I reported it here: https://github.com/realworldocaml/mdx/issues/147
- I disabled a shell snippet with an `ocamlfind` invocation. The current dune port for findlib/ocamlfind has a few issues and I don't think it builds the `ocamlfind` executable or at least doesn't do so in a `dune` friendly way. Furthermore, it …
=> Duniverse: Fix Files, Modules and Programs chapter

book/command-line-parsing/README.md
On #3100
Skipped `md5.exe` examples because they depend on `cryptokit` that is not yet compatible with dune.
The syntax `./_build/default/abc.exe` cannot be used anymore because dune will find the root of the project and the paths will be `../../../../_build/default/examples/code/ ...`
so I changed to `dune exec -- ./cal.exe`.
=> Duniverse: Fix command line parsing chapter

book/maps-and-hashtables/README.md
On #3100
~~Updated the outputs to OCaml 4.08.~~
Paths in the backtraces contains the prefix `duniverse/lib_name`, is that a problem ?
=> Duniverse: Fix maps and hashtables chapter

book/first-class-modules/README.md
This depends on #3100, only the last two commits are releveant to this PR.
One toplevel snippet's evaluation was incorrect.
I also marked another one as non-deterministic since it list the directories in `/var` which is highly likely to be different for every machine it's ran on.
=> Duniverse: Fix First Class Modules chapter

book/parsing-with-ocamllex-and-menhir/README.md, examples/code/parsing-test/test.ml
On #3100 
`Command.Spec.file` does not exists. I replaced it with `string`, is that correct ?
=> Duniverse: Fix parsing with ocamllex and menhir chapter

book/classes/README.md, examples/code/classes-async/multiple_inheritance.ml, examples/code/classes-async/multiple_inheritance_wrong.ml, examples/code/classes-async/shapes/shapes.ml, examples/code/classes-async/verbose_shapes.ml
This depends on #3100, only the last two commits are relevant to this PR.
I had to disable the `dune build` shell snippet as it relies on `async_graphics` which in turn rely on `graphics` and that last one hasn't been dunified.
Rest is just some small fixes to `.ml` files.
=> Duniverse: Fix Classes chapter

book/compiler-frontend/README.md, examples/code/front-end/doc.ml
Depends on #3100
Skipped examples requiring findlib.
`ocp-indent` depends on findlib and we did not manage to make it work properly yet.
=> Duniverse: Fix compiler frontend chapter

book/files-modules-and-programs/README.md
It seems that the cycle isn't always dislayed in the same order!
=> Mark cycle detection example as non-deterministic

book/foreign-function-interface/README.md, book/foreign-function-interface/prelude.ml, dune-get, duniverse/ctypes/src/ctypes-foreign-threaded/dune, examples/code/ffi/datetime/dune, examples/code/ffi/hello/dune, examples/code/ffi/ncurses/dune, examples/code/ffi/qsort/dune
This PR finishes to fix the FFI chapter:
- It disables `corebuild` shell blocks as it depends on `ocamlfind` which isn't provided in the dune port yet
- It adds explicit dependencies to `ctypes-foreign.threaded` as the dune port virtual library part needs fixing
- It updates `ctypes` in the duniverse to fix a warning from one of its dune files
=> Fixes for FFI chapter

Dockerfile, book/parsing-with-ocamllex-and-menhir/README.md
Because menhir depends on ocamlfind, installing it through opam
in the CI may lead to issues where the opam ocamlfind is picked over
the duniverse one or where the two conflicts.
It's probably better to wait for a proper dune port.
=> Do not install menhir in CI

book/guided-tour/prelude.ml
We should never use `#require "a,b";;` as that result in neither being loaded if there's an issue with one and that makes it a bit hard to debug!
`ppx_jane` is not loaded properly because `bin_prot` is not installed in `_build/install` for some reason, we can work this out later as the chapter's tests now build!
=> Fix guided tour's prelude.ml

book/files-modules-and-programs/README.md, examples/code/files-modules-and-programs/session_info/session_info.ml
According to the explanation, it should be `Username` rather than `Hostname`.
=> Fix type error of the example in chapter 4

book/variables-and-functions/README.md
Hello!
Above all, thank you for writing this excellent book.
I found a type error in example for using `^>` operator from `variables-and-functions` chapter.
This commit contains the fix for this error, and to explain my fix, I added some preliminary contents, so please consider it too.
I really enjoying this book. Thank you.
=> Fix type error in the example in variables-and-functions chapter

book/concurrent-programming/README.md
Various small improvements and cleanups to the Async chapter.  This includes making some things "notes" that were previously asides (which seem not to be supported anymore in the toolchain), and also taking the existing monitor section and just converting it to a note, on the theory that it's tricky stuff that one can skip at first.
=> Async small fixes

book/compiler-backend/README.md, book/compiler-frontend/README.md, book/foreign-function-interface/README.md, book/garbage-collector/README.md, book/imperative-programming/README.md, book/json/README.md, book/lists-and-patterns/README.md, book/maps-and-hashtables/README.md, book/objects/README.md, examples/code/back-end/pattern_monomorphic_small.ml
Most with notes, one with a warning. Asides (in this case, marked as sidebars) are currently ignored, and it's not clear what distinction is intended between sidebar and note.
The diff is easier to read if you turn off whitespace in the diff.  Some whitespace-only changes were made because my editor is configured to remove trailing whitespace on save.
=> replaced all remaining asides

book/guided-tour/README.md
...as its unnecessary to the point being made for OCaml
Addresses and closes #2472:
> This paragraph equates compiled languages with statically typed
> languages. The fact that LISP and Scheme can be compiled, doesn't
> make them statically typed.
=> elide the comparison of OCaml to other languages

static/js/prism.js
my fix to c74ef8bf896c5ea21c97ccfb339ce23278420213 accidentally
put the wrong version of the JavaScript in.  This one removes
some debug sprinkles and introduces the patch that fixes
the #3079 reported issue of `<fun>` not rendering from toplevel
output.
=> actually fix html toplevel syntax highlighting

book/guided-tour/README.md
Little typo in guided tour, ':' instead of '.'.
=> Fix little typo in guided tour

book/maps-and-hashtables/README.md
A tiny typo. From `%%hash` to `%hash`.
=> fix hash shorthand

book/json/README.md, book/json/examples/json/github_org_info/dune, book/json/examples/json/github_org_info/github_org_info.ml
In summary, the `Core_extended.Shell` seems to have been moved to its
own library `shell`.
See https://discuss.ocaml.org/t/ann-v0-12-release-of-jane-street-packages/3499
The `core_extended` library https://github.com/janestreet/core_extended
has reorganised their code
https://discuss.ocaml.org/t/ann-v0-12-release-of-jane-street-packages/3499
While trying the `github_org_info` example I ran into the following
problem:
```
dune exec -- ./github_org_info.exe janestreet
File "dune", line 15, characters 32-45:
15 |   (libraries core yojson atdgen core_extended)
^^^^^^^^^^^^^
Error: Library "core_extended" not found.
Hint: try: dune external-lib-deps --missing ./github_org_info.exe
```
Similar to https://github.com/janestreet/core_extended/issues/22 the
`core_extended` library was installed: …
=> json: Use Shell instead of Core_extended.Shell

book/error-handling/README.md
A few formatting fixes; removing a redundant colon symbol between index tags.
=> Error handling: code formatting fixes

book/files-modules-and-programs/README.md
Fixes https://github.com/realworldocaml/book/issues/3226
Change grep command in the [Single-file-programs chapter](http://dev.realworldocaml.org/files-modules-and-programs.html#single-file-programs) to be compatible with both Linux **and** macOS.
=> Files chapter: grep command compatibility with macOS

Makefile, README.md, dune-get
Fixes #3157 
This updates both the duniverse and the `Makefile` so that we now use mdx's master branch.
=> Upgrade to mdx's master

book/concurrent-programming/README.md
I dont think I actually did anything special to fix this -- it just
seems to work with the newer short paths in 4.08+
closes #3189
=> remove note about the conduit type alias, since it is no longer leaked

Dockerfile
dune 2.0.0 was marked uninstallable in https://github.com/ocaml/opam-repository/pull/15555
=> upgrade to dune 2.0.1

README.md
This is related to https://github.com/realworldocaml/book/commit/bcc164581f3e57ce98ec7a286a42c37e9211742d
The README.md file mentions that we can set up the environment by running 
```
opam install dune=2.0.0
```
But this doesn't work anymore
```
> opam install dune=2.0.0
[ERROR] dune = 2.0.0 unmet availability conditions: false
```
This PR simply bumps the dune version to `2.0.1`, which is in line with the [Dockerfile](https://github.com/realworldocaml/book/blob/917b1fdda5f67ad11b8e1e46aa8b681e367dc430/Dockerfile#L13)
=> Bump dune version in README.md

book/guided-tour/README.md
In the "OCaml as a Calculator" section, the text should read "1.0 /. 3.0 is a third", instead of "1 / 3.0".
```
utop> 1.0 /. 3.0;;
- : float = 0.33333333333333331
```
=> Use "1.0 /. 3.0" for a third

book/guided-tour/README.md
Why are there two "Hello_World.TXT" strings in this example? Was the second list entry meant to be "Hello_World.txt"?
```
utop> List.map ~f:downcase_extension
[ "Hello_World.TXT"; "Hello_World.txt"; "Hello_World"]
;;
```
=> Use lowercase txt in Options example

Makefile, dune-get
Duniverse now allows specifying whether we want to use git submodules or plain source vendoring. This has to be set at `duniverse init` time.
This updates our Makefile targets and our `dune-get` file so that we keep on with our plain vendoring approach.
=> Update Makefile and dune-get for latest duniverse

book/variables-and-functions/README.md
In the second sentence in the "Variables" section, there needs to be a whitespace between `top-level` and `let` in the sentence, "... top-levellet binding with the following syntax.".
The output of `make test`.
```
$ make test
dune test
```
=> Use whitespace between top-level and let

book/guided-tour/README.md
In the "Nesting lets with let and in" section, the value of "x" is '3' instead of the following:
```
utop> x;;
Line 1, characters 1-2:
Error: Unbound value x
```
If one continuously evaluates the chapter examples in a utop session, the value of 'x' gets set as '3' from the "Tuples" section:
```
let (x,y) = a_tuple;;
val x : int = 3
val y : string = "three"
```
Hence, an unused variable "z" is used to illustrate the let binding.
=> Use z instead of x in Nesting Lets with Let and In

book/variables-and-functions/README.md, book/variables-and-functions/dune, book/variables-and-functions/examples/abs_diff.mli, book/variables-and-functions/examples/htable_sig1.ml, book/variables-and-functions/examples/htable_sig2.ml, book/variables-and-functions/examples/numerical_deriv_alt_sig.mli, book/variables-and-functions/examples/substring_sig1.ml, book/variables-and-functions/examples/substring_sig2.ml
This removes unecessary examples form the chapter and replaces them by unchecked blocks.
This is strictly equivalent since the examples weren't checked either given they're comprised of single mli files.
In the future we'd like to have native support for checking interfaces in MDX.
=> Clean examples in variables-and-functions chapter

book/lists-and-patterns/README.md
More meaningful than the names used, and fits the pattern used in the rest of the chapter.  Alternative solution to: #3284
=> Use acc and hd in List.fold example

book/lists-and-patterns/README.md
...in benchmarks.  Turns out they weren't needed.
=> remove unnecessary ignores

book/error-handling/README.md
Exn.backtrace no longer exists.  Fixed.
=> fixed backtrace

README.md
This adds a section to the README describing the new example workflow, how to use it and how to set it up for new chapters.
=> Describe new example workflow in README

book/prologue/README.md
Hi there,
Thanks for the great book! I added some commas where they were needed:
> libraries tools and techniques
but also made a judgement call and suggested ", as well as" instead of the first "and". If you'd like, let me know and I can change that back to ", and".
Thanks!
Brian
=> Add missing commas

Makefile, README.md, dune
Closes #3135.
This PR adds a non-deterministic dune profile that allows running the non-deterministic mdx tests. It also updates the non-deterministic tests README section!
=> Add a non-deterministic dune profile to run mdx non-det tests

book/guided-tour/README.md, book/records/README.md, book/variants/README.md
Used the MDX feature where you can write down snippets of OCaml without getting toplevel style type-throwback.  This eliminates some annoying duplication of types. 
Then end result seems clearly easier to read, but it's a little bit odd to change the presentation so that somethings look like they're in a toplevel session and some don't, while to follow along, the reader would need to do it all in a toplevel session.
=> Eliminate some type throwback

book/command-line-parsing/README.md, book/command-line-parsing/examples/correct/md5_with_custom_arg/md5.ml
Also, cleaned up an example that created an arg-type in an unsanitary way, by running exit directly instead of just raising.
=> removed out-of-date table, talked about location of argument types

book/guided-tour/README.md
matching case `Segment { endpoint1; endpoint2 }` and returning false raises compilation warnings/errors for unused variables.  
Using _ makes Segment definition quite idle but not it compiles fine.
=> Unused endpoint1 and endpoint2 in Segment case

book/lists-and-patterns/README.md
The "online docs" link in the [`More useful list functions`](https://dev.realworldocaml.org/lists-and-patterns.html#more-useful-list-functions) of the `Lists and patterns` chapter leads to a [broken link](http://realworldocaml.org/doc). 
Technically, it should lead to: https://ocaml.janestreet.com/ocaml-core/latest/doc/, but since the section is on the `List` functions from `Base`, I believe it should lead to: https://ocaml.janestreet.com/ocaml-core/latest/doc/base/Base/List/index.html
=> Fix online list docs broken link

book/lists-and-patterns/README.md
In the [FILTERING WITH LIST.FILTER AND LIST.FILTER_MAP](https://dev.realworldocaml.org/lists-and-patterns.html#filtering-with-list.filter-and-list.filter_map) section, the code example references the `List.dedup_and_sort` function while the text references a `List.dedup` function which does not exist in the `List` module of `Base`. I am making the text consistent with the code example by changing:
`... List.dedup to remove duplicates.` -> `... List.dedup_and_sort to return the list with duplicates removed and in sorted order.`
=> Fix list-and-patterns section reference to List.dedup_and_sort

bin/examples-rules/examples_rules.ml, book/command-line-parsing/examples/dune.inc, book/concurrent-programming/examples/dune.inc, book/data-serialization/examples/dune.inc, book/error-handling/examples/dune.inc, book/files-modules-and-programs/examples/dune.inc, book/guided-tour/examples/dune.inc, book/imperative-programming/examples/dune.inc, book/maps-and-hashtables/examples/dune.inc, book/testing/examples/dune.inc, book/variants/examples/dune.inc
Previously, example rules would invoke dune using `(run dune ...)`.
When seeing `(run prog ...)`, dune first looks for a public executable named `prog` in the workspace before looking at the environment (`PATH`).
In the case of this repository, it happens that a dune executable is in the workspace, because the sources of dune-build-info are there and they are the same as the dune sources.
When building the examples, this dune (2.6 at the moment) will be picked, and it will try to read dune-package files for the other packages. If these have been written by a dune in the environment with a higher version, it will fail with an error. Effectively, this puts a constraint that dune in the environment should be older than the vendored one.
To fix this, the `(run dune ...)` action is replaced by …
=> Example rules: pick dune in PATH

bin/bin/app.ml, bin/lib/book.ml, bin/lib/rules.ml, bin/lib/toc.ml, bin/lib/toc.mli, static-wip/dune.inc
Fixes #3376
Chapter numbering was incorrect in the generated website and any chapter preceding a wip chapter contained a dead link to it instead of a link to the next non wip chapter. This is fixed by always filtering the table of content early.
=> Fix handling of WIP chapters

book/lists-and-patterns/README.md
There are few minor typos I've encountered while going through the chapter 3. Thank you for the great book and making it available for everyone!
I've formatted the diff using line width = 77 which I inferred by looking at the rest of the text, let me know if there's an official way of formatting the md files.
The changes are `s/astring/a string/` and `s/useful is/useful it is/`, but the diff is larger due to reformatting.
=> Fix typos in lists-and-patterns.

book/concurrent-programming/README.md, book/maps-and-hashtables/README.md, book/records/README.md, book/variables-and-functions/README.md
References in two places were linking to the guided tour while it's
clear from the context that they should link to the dedicated chapter
about imperative programming.
References in two other places were titled "Imperative Programming 1",
in contrast with the rest titled simply "Imperative Programming".
=> Fix references to Imperative Programming chapter.

book/book.yml, book/compiler-frontend/README.md, book/cup-template.tex, book/garbage-collector/README.md, book/imperative-programming/README.md, book/lists-and-patterns/README.md, book/runtime-memory-layout/README.md, static-wip/dune, static/dune
Use markdown format for pandoc rather than the HTML, and setup
the appropriate latex figure magic
=> include images in PDFs

bin/pandoc-rwo/README.md, bin/pandoc-rwo/dune, bin/pandoc-rwo/pandoc.ml, bin/pandoc-rwo/pandoc.mli, bin/pandoc-rwo/pandoc_rwo.ml, book/book.yml, book/cup-template.tex, book/garbage-collector/README.md, book/lists-and-patterns/README.md, book/variables-and-functions/README.md, book/variants/README.md, static-wip/dune, static/dune
this uses a pandoc filter to rewrite markdown notes to tex. Vendors pandoc fork to support <div> with upstream PR  at https://github.com/smimram/ocaml-pandoc/pull/2
=> Add callouts to pdf

book/lists-and-patterns/README.md
Fixes a typo in "Lists and Patterns" chapter.
=> Fix typo in lists-and-patterns

book/testing/README.md
This should fix issues of disappearing whitespace.
=> removed whitespace in front of shell snippets

book/install.html
It was linking to https://github.com/ocaml-ppx/ocamlformat instead
=> Fix link to ocp-indent

book/gadts/README.md
Fix typo 'The syntax here is requires' -> 'The syntax here requires'
=> [gadts] Fix typo 'syntax here is requires' -> 'syntax here requires'

book/gadts/README.md
To leave the most complicated section (narrowing the possibilities) to the end.
=> reworked order of GADT examples

book/platform/README.md
I've just found a little typo regarding the "test" directory.
=> fix typo referencing the test directory

book/concurrent-programming/README.md, book/garbage-collector/README.md
These were only used for `mdx rule` but since the code uses the dune `mdx` stanza now this is declared in the `dune` file instead.
=> Remove `require-package` labels

book/objects/README.md
There are escaped ` ``` ` in generated md (and pdf) due to no newline between code and paragraph
Before:
After:
=> add empty line for code-paragraph separation

bin/bin/convert_md.ml
since upgrading to mdx 2.0, we have semicolons everywhere, so
fix up the book pdf output
=> fix pdf and html output wrt semicolons

book/imperative-programming/README.md, book/runtime-memory-layout/README.md
Add coverage of bytes in two chapters: imperative programming and runtime-representation of values. Also, changed a graphic related to strings to just be an inline plain-text representation of the equation.
Closes #3529
=> add coverage of bytes

README.md
The min supported version was bumped several times so now it you install dune2.0.1 you can't run make.
Also, you need to have dozens other packages to successfully compile the book, for example:
basictex, pandoc and dozen packages like `tlmgr install framed `.
and there are build failures https://github.com/realworldocaml/book/issues/3547
=> Update dune version in readme.

book/foreign-function-interface/README.md
MDX 1.x deprecates top-level phrases that don't end with `;;`, 2.0 emits fixed versions and 3.0 will stop supporting that.
=> Add double semicolons to be forward compatible with MDX

book/variables-and-functions/README.md
Minor copy changes, a bunch of \noindents, and a more material cleanup of formatting and text of bulleted list about where labeled arguments are useful.
=> Clean up variables and functions

book/parsing-with-ocamllex-and-menhir/examples/parsing/lexer.mll
Commit 4c244abfa67cea3b465a9df3e7e357c58d73ae11 removed `next_line` so this one also switches to `Lexing.new_line` accordingly.
=> Fix missing `next_line` reference

book/guided-tour/README.md, book/imperative-programming/README.md, book/lists-and-patterns/README.md, book/records/README.md
For some reason when running the tests I missed out the remaining error messages, so to be sure this time I cleaned the build and built it from scratch.
Really embarassing, that.
=> Add remaining semicolons that were left out before

book/platform/.ocamlformat, book/platform/README.md, book/platform/examples/correct/hello/.ocamlformat, book/platform/examples/correct/hello/lib/msg.mli, book/platform/examples/correct/hello/test/hello.ml, book/platform/examples/ocamlformat
Not a lot of changes
- Some small language and formatting tweaks
- Added ocamlformat, mostly to fix some over-long lines, but it reordered some doc comments to match the ordering in the rest of the book. (Also, uncovered a bug with an unmatched, quoted (** inside a comment
- Changed some words (customisation -> customization) to the US version. We're going by US spellings, right?
- clarified language around inline tests
=> Review ocaml platform

book/command-line-parsing/README.md, book/compiler-backend/README.md, book/compiler-frontend/README.md, book/concurrent-programming/README.md, book/data-serialization/README.md, book/error-handling/README.md, book/files-modules-and-programs/README.md, book/first-class-modules/README.md, book/foreign-function-interface/README.md, book/gadts/README.md, book/garbage-collector/README.md, book/guided-tour/README.md, book/imperative-programming/README.md, book/json/README.md, book/lists-and-patterns/README.md, book/maps-and-hashtables/README.md, book/objects/README.md, book/parsing-with-ocamllex-and-menhir/README.md, book/platform/README.md, book/records/README.md, book/runtime-memory-layout/README.md, book/testing/README.md, book/variables-and-functions/README.md, book/variants/README.md
Most were 5, some were not. Should all be the same now.
Also, fixed some titles in notes that should have marked some things as code but didn't. And fixed a handful of cross-references.
=> changed all notes to 4 #'s

book/platform/README.md
* redundant "is"
* typo in explicitly
=> fix platform typos

book/variables-and-functions/README.md
It was hard to render, and it's annoying to keep up to date. Better to just point out its existence, and put in a URL.
=> Get rid of precedence table

book/classes/README.md, book/classes/examples/shapes/shapes.ml, book/classes/examples/verbose_shapes.ml, book/maps-and-hashtables/README.md
One could also remove the extraneous parentheses around `Float.of_int radius`.
I get an error when running this code. This is because Base/Core removes the polymorphic nature of `<=`. Not sure how to best fix it, if one wants to follow the spirit of that example. Maybe
```
method private contains x' y' =
let dx = x' - x in
let dy = y' - y in
let dist = Float.sqrt (Float.of_int (dx * dx + dy * dy)) in
Float.(dist <= of_int radius)
``` 
But why not avoid `Float` altogether ?
```
method private contains x' y' =
let dx = x' - x in
let dy = y' - y in
dx * dx + dy * dy <= radius * radius
```
@yminsky : tell me if that's ok and I'll gladly implement that latter solution in both instances.
=> Chapter 'Classes': simplify code
