- book/install.html
begins to address the comments in #2804 regarding camlp4 vs ppx
> installation: fixup markup and refresh installation instructions

- book/03-lists-and-patterns.html
> typo: teh -> the

- book/01-guided-tour.html
- examples/code/guided-tour/main.topscript
- examples/code/guided-tour/sum/jbuild
- examples/code/guided-tour/sum/sum.ml
I pushed through the use of Base in the guided tour. This involved explaining a bit more about polymorphic compare and the lack thereof in Base, as well as explaining how local opens work. I also included a description of Base, Core_kernel and Core and how they fit in. 
Maybe the weirdest thing in this code is Base's **. operator, which I'm not sure how happy I am about, all in. I've started off a discussion about that amongst the Base devs.
> Base in guided tour

- book/03-lists-and-patterns.html
> fix typo: missing 'does not'

- bin/bin/app.ml
- bin/bin/jbuild
- bin/lib/rwo_core2.ml
- bin/lib/rwo_core2.mli
- bin/lib/rwo_scripts.ml
A minor tweak, as I get to know the RWO tools. Also, made a few other very minor changes to the scripts elsewhere, including getting rid of a case of unbounded parallelism (replacing a List.map with a Deferred.List.map, the latter of which operates sequentially.
> migrated to using new-style Command API

- book/05-records.html
- examples/code/records/main.topscript
- examples/code/records/main2.topscript
Pretty simple. I deleted some work I'd done to explain all the various and sundry OCaml string syntaxes, because it wasn't necessary here. We'll probably need it somewhere, eventually.
> Base in records

- book/07-error-handling.html
- examples/code/error-handling/main.topscript
Pretty simple; had to open Stdio in a few places, and some other minor tweaks.
> Base in error handling

- book/06-variants.html
- examples/code/variants/blang.topscript
- examples/code/variants/catch_all.topscript
- examples/code/variants/logger.topscript
- examples/code/variants/main.topscript
> Base in variants

- book/02-variables-and-functions.html
- examples/code/variables-and-functions/main.topscript
OK, this one looks better. The changes are quite simple.
> Base in variables and functions

- examples/code/imperative-programming/dictionary.ml
- examples/code/imperative-programming/dictionary.mli
- examples/code/imperative-programming/dlist.ml
- examples/code/imperative-programming/dlist.mli
- examples/code/imperative-programming/examples.topscript
- examples/code/imperative-programming/fib.topscript
- examples/code/imperative-programming/file.topscript
- examples/code/imperative-programming/file2.topscript
- examples/code/imperative-programming/for.topscript
- examples/code/imperative-programming/lazy.topscript
- examples/code/imperative-programming/letrec.topscript
- examples/code/imperative-programming/memo.topscript
- examples/code/imperative-programming/order.topscript
- examples/code/imperative-programming/printf.topscript
- examples/code/imperative-programming/time_converter2.ml
- examples/code/imperative-programming/value_restriction.topscript
Lots of small changes here, much of which was fixing breakage that was already committed.
> Base in imperative programming

- bin/bin/app.ml
- bin/lib/rwo_scripts.ml
- bin/lib/rwo_scripts.mli
Remove whitespaces, use `ocp-indent and remove a dead comment.
> Minor Cleanups

- book/05-records.html
> Corrected typo.

- Makefile
- bin/bin/app.ml
- bin/lib/rwo_book.ml
- bin/lib/rwo_book.mli
- bin/lib/rwo_scripts.ml
- bin/lib/rwo_scripts.mli
- topexpect/src/main.ml
> Remove dead code

- examples/code/async/main.mlt
- examples/code/classes/iter.mlt
- examples/code/command-line-parsing/command_types.mlt
- examples/code/ffi/posix.mlt
- examples/code/imperative-programming/fib.mlt
- examples/code/imperative-programming/file2.mlt
- examples/code/imperative-programming/letrec.mlt
- examples/code/imperative-programming/memo.mlt
- examples/code/imperative-programming/value_restriction.mlt
- examples/code/imperative-programming/weak.mlt
- examples/code/maps-and-hash-tables/main.mlt
- examples/code/records/main2.mlt
- examples/code/variants/logger.mlt
- examples/code/variants/main.mlt
4.06 has changed the way weak polymorphic variables are printed. Also, there are a few breakage due to the switch to Base, which can be fixed by following commits.
My plan is to fix the broken toplevel scripts with new, more targeted PRs later on.
> Update toplevel scripts

- book/09-functors.html
- examples/code/fcm/main.mlt
- examples/code/fcm/query_handler.mlt
- examples/code/functors/foldable.ml
- examples/code/functors/fqueue.ml
- examples/code/functors/main.mlt
Move the first-class-modules and functors chapters to Base, mostly.
> More base conversions

- book/13-maps-and-hashtables.html
- examples/code/maps-and-hash-tables/main.mlt
Add another small section to the maps chapter, covering how you use [@@deriving] on map or set types.
> Using maps in deriving

- Dockerfile
- bin/lib/jbuild
- bin/lib/rwo_html.ml
- bin/lib/rwo_html.mli
- rwo.opam
It's hard to test that the HTML output is equivalent, but the website seems to render correctly and is visually similar to what it was before.
> Remove ocamlnet

- bin/lib/rwo_html.ml
> Fix another HTML rendering bug

- bin/lib/rwo_html.ml
- book/00-prologue.html
- book/faqs.html
- book/install.html
Thanks to @pmetzger for the reports.
> Fix more rendering bugs

- examples/code/maps-and-hash-tables/main.mlt
- examples/code/maps-and-hash-tables/map_vs_hash/run_map_vs_hash.sh
- examples/code/maps-and-hash-tables/map_vs_hash2/run_map_vs_hash2.sh
A few small fixes enabled by the upgrade to 0.11
> 0.11 related fixes

- examples/code/classes/binary.mlt
- examples/code/classes/initializer.mlt
- examples/code/classes/istack.mlt
- examples/code/classes/iter.mlt
- examples/code/classes/stack.mlt
- examples/code/objects/immutable.mlt
- examples/code/objects/polymorphism.mlt
- examples/code/objects/row_polymorphism.mlt
- examples/code/objects/stack.mlt
- examples/code/objects/subtyping.mlt
Switch to Base in the Objects and Classes chapters
> Base in objects and classes

- book/install.html
> html: add missing code tag

- static/css/app.css
This changes the layout from:
to:
> reformat CSS + larger column for contents 

- cram/lib/cram.ml
> cram: fix promotion of non-determinitic tests

- static/css/app.css
This PR adds a small, fixed, BETA ribbon to the website:
> Add a beta ribbon

- examples/code/variants/logger.mlt
> Fixed small compilation error

- book/variants.md
> variants: Add a missing word

- book/guided-tour.md
And some unnecessary white space.
> remove some obsolete language

- README.md
/cc @christophe-riolo 
Hopefully this makes things a bit more clear.
> Add build/test instructions to the README

- book/compiler-backend.md
Hi, I stumbled upon this sentence reading compiler backend chapter.
Following a proposal for a slight improvement
> Update Compiler backend

- book/json/README.md
> fix yojson link

- book/concurrent-programming/README.md
Reverts https://github.com/realworldocaml/book/pull/3043
> reverted bad PR

- book/dune
- book/toc.scm
- rwo.opam
- static/dune
The Docker image has been updated before doing that PR so #3027 should really be fixed now.
> Remove the GADT chapter from toc file and use latest mdx

- book/records/README.md
- examples/code/imperative-programming/time_converter/time_converter.ml
I don't want to open issue per thing so that's why I'm taking all of the things here. 
If any of all fixes are not needed just let me know :) I'm still reading the book and that's the reason why it's a draft.
Fixes:
Error (warning 3): deprecated: Core.stdin
[since 2016-04] Use [In_channel.stdin]```
> Couple of tweaks

- book/classes/dune
- book/command-line-parsing/dune
- book/compiler-backend/dune
- book/compiler-frontend/dune
- book/concurrent-programming/dune
- book/data-serialization/dune
- book/error-handling/dune
- book/files-modules-and-programs/dune
- book/first-class-modules/dune
- book/foreign-function-interface/dune
- book/functors/dune
- book/garbage-collector/dune
- book/guided-tour/dune
- book/imperative-programming/dune
- book/json/dune
- book/lists-and-patterns/dune
- book/maps-and-hashtables/dune
- book/objects/dune
- book/parsing-with-ocamllex-and-menhir/dune
- book/ppx/dune
- book/prologue/dune
- book/records/dune
- book/runtime-memory-layout/dune
- book/variables-and-functions/dune
- book/variants/dune
Depends on #3100, only the last two commits are relevant to this PR.
The dependencies of the rule weren't properly specified, this PR fixes it.
I'm doing this on top of #3100 to avoid a rebase hassle there.
> Duniverse: Fix mdx rule invocations

- book/records/README.md
- dune-get
- duniverse/seq/.gitignore
- duniverse/seq/LICENSE
- duniverse/seq/Makefile
- duniverse/seq/README.md
- duniverse/seq/dune-project
- duniverse/seq/seq.opam
- duniverse/seq/src/dune
- duniverse/seq/src/select_version.ml
- duniverse/seq/src/seq_alias.ml
- duniverse/seq/src/seq_alias.mli
- duniverse/seq/src/seq_redef.ml
- duniverse/seq/src/seq_redef.mli
Depends on #3100, I'm leaving this as draft until it's merged! Note that only the last 4 commits are relevant to this PR.
Not much going on here:
- The toplevel was missing a `#require "re"`
- I removed the deprecated `#require "re.posix"`
- I moved from the deprecated `Re.get` to `Re.Group.get`
> Duniverse: Fix Records chapter tests

- book/imperative-programming/README.md
- examples/code/imperative-programming/dictionary.ml
- examples/code/imperative-programming/dictionary.mli
- examples/code/imperative-programming/dlist.ml
- examples/code/imperative-programming/time_converter/time_converter.ml
This depends on #3100, only the last commit is relevant to this PR.
Most of the changes here were about bringing the`.ml` files back to sync with the chapter snippets.
You'll also note a bunch of `;;` added by the new `mdx`.
> Duniverse: Fix imperative programming chapter

- book/data-serialization/README.md
- examples/code/sexpr/read_foo/read_foo.ml
- examples/code/sexpr/read_foo_better_errors/read_foo_better_errors.ml
On #3100
Update outputs to new version of Core.
> Duniverse: Fix data serialization chapter

- book/imperative-programming/README.md
To address https://github.com/realworldocaml/book/issues/3055
> Swap jbuilder with dune - closes #3055

- book/guided-tour/README.md
Alternative fix to the problem pointed out in #3059.
> Fix guided tour log entry comment

- book-pkgs
- book/command-line-parsing/README.md
- dune-get
- examples/code/command-line-parsing/md5/dune
- examples/code/command-line-parsing/md5/md5.ml
- examples/code/command-line-parsing/md5_as_filename/dune
- examples/code/command-line-parsing/md5_let_syntax/dune
- examples/code/command-line-parsing/md5_let_syntax/md5.ml
- examples/code/command-line-parsing/md5_let_syntax2/dune
- examples/code/command-line-parsing/md5_let_syntax2/md5.ml
- examples/code/command-line-parsing/md5_multiarg/dune
- examples/code/command-line-parsing/md5_multiarg/md5.ml
- examples/code/command-line-parsing/md5_sequence/dune
- examples/code/command-line-parsing/md5_sequence/md5.ml
- examples/code/command-line-parsing/md5_succinct/dune
- examples/code/command-line-parsing/md5_succinct/md5.ml
- examples/code/command-line-parsing/md5_with_custom_arg/dune
- examples/code/command-line-parsing/md5_with_custom_arg/md5.ml
- examples/code/command-line-parsing/md5_with_default_file/dune
- examples/code/command-line-parsing/md5_with_default_file/md5.ml
- examples/code/command-line-parsing/md5_with_flags/dune
- examples/code/command-line-parsing/md5_with_flags/md5.ml
- examples/code/command-line-parsing/md5_with_optional_file/dune
- examples/code/command-line-parsing/md5_with_optional_file/md5.ml
- examples/code/command-line-parsing/md5_with_optional_file_broken/dune
- examples/code/command-line-parsing/md5_with_optional_file_broken/md5.ml
followup to #3140 
@yminsky, is the let-syntax example used anywhere yet in the text?
> Update CLI chapter to remove cryptokit and use dune exec

- book/files-modules-and-programs/README.md
- examples/code/files-modules-and-programs/freq-with-sig-mismatch/counter.ml
- examples/code/files-modules-and-programs/freq-with-sig-mismatch/counter.mli
Fix some small mistakes in this section.
> Improve files modules and programs

- book/files-modules-and-programs/README.md
From https://github.com/realworldocaml/book/issues/3161
> fixed typo

- book/faqs.html
Fixes https://github.com/realworldocaml/book/issues/2623
> blagged -> bagged

- Dockerfile
We should keep to the latest stable version of dune for the tests
> update to dune 1.11.3

- book/variants/README.md
- book/variants/examples/variants-termcol-annotated/terminal_color.ml
> fixed mistake in polymorphic variants example

- book/concurrent-programming/README.md
This has been breaking the build of late.
> Add a missing non-determinism marker

- book/maps-and-hashtables/README.md
Right now, the Maps chapter only talks about Comparator, but Comparable is most often what you actually want.  Explain how Comparable works, and add an example.
> Explain Comparable in addition to Comparator

- book/error-handling/README.md
Not_found should be Key_not_found
> error-handling fixed typo and indent

- bin/lib/book.ml
Also removed duplicated head tag, before it was `<head><head>`
> Add chapter title to html.head.title

- book/records/README.md
Last function argument is on the next line.
> Records chapter: code formatting in service_info_of_string example

- book/records/README.md
"credentials" field is slightly misaligned
> Records chapter: fix deriving fields code example formatting

- book/variants/README.md
Pattern matching formatting is a bit off in some places.
> Variants chapter: code format fixes

- book/parsing-with-ocamllex-and-menhir/README.md
> fix: Change Camomile link to the new Github location

- README.md
> Update repository layout README's section

- Dockerfile
- book/book.tex
Also update pandoc to 2.9.0 as that is what this CR was tested against.
Fixes #3224
> update LaTeX output for prettier code listings

- book/imperative-programming/README.md
> Small fixes to Imperative Programming chapter

- book/foreign-function-interface/README.md
- book/foreign-function-interface/dune
> Replace corebuild with ocaml-print-intf

- book/imperative-programming/README.md
- book/imperative-programming/examples/correct/dictionary/dictionary.ml
- book/imperative-programming/examples/correct/dictionary/dictionary.mli
Also, fix a number of other small issues, including updating references from Core to Base and Core_kernel, and updating references to ocaml 4.01 to OCaml 4.09!
> Remove polymorphism in hashtbl example

- book/imperative-programming/README.md
Some changes I forgot to bring along
> Small tweaks to hashtbl example

- book/records/README.md
> fixed malformatted note

- book/classes/prelude.ml
- book/command-line-parsing/prelude.ml
- book/compiler-backend/prelude.ml
- book/compiler-frontend/prelude.ml
- book/concurrent-programming/README.md
- book/concurrent-programming/prelude.ml
- book/data-serialization/README.md
- book/data-serialization/prelude.ml
- book/first-class-modules/README.md
- book/first-class-modules/prelude.ml
- book/foreign-function-interface/prelude.ml
- book/functors/README.md
- book/functors/prelude.ml
- book/garbage-collector/prelude.ml
- book/json/prelude.ml
- book/maps-and-hashtables/README.md
- book/maps-and-hashtables/prelude.ml
- book/objects/prelude.ml
- book/parsing-with-ocamllex-and-menhir/prelude.ml
- book/ppx/prelude.ml
Removed the opening of ppx_jane from the remaining preludes that included it.
> Remove remaining implicit ppx jane

- book/files-modules-and-programs/README.md
- book/files-modules-and-programs/examples/erroneous/freq-with-missing-def/counter.ml
- book/files-modules-and-programs/examples/erroneous/freq-with-missing-def/counter.mli
> cleaned up broken example

- book/guided-tour/README.md
> moved observation about double-semis earlier

- book/json/README.md
- book/json/examples/read_json/read_json.ml
> Fixes broken example from JSON chapter that wasn't being built.

- book/functors/README.md
> Fixes 3389

- book/prologue/README.md
Hi! I'm very new to OCaml. I found this book really beneficial to me as soon as I started reading it. Thanks for the awesome work of you all!
Anyway, when reading prologue, I noticed there was a tiny typo, so this PR fixes it :)
> Fix typo in prologue

- book/parsing-with-ocamllex-and-menhir/README.md
- book/parsing-with-ocamllex-and-menhir/examples/parsing-test/lexer.mll
- book/parsing-with-ocamllex-and-menhir/examples/parsing/lexer.mll
Rebased version of https://github.com/realworldocaml/book/pull/3239
> use pos_cnum to reset bol in lexers (followup to 3239)

- book/testing/README.md
In particular: Alcotest, qcheck, afl, crowbar, bun.
> Mention other testing tools

- book/files-modules-and-programs/README.md
Small textual change.
Closes #3457
> resolve #3457

- book/guided-tour/README.md
> add note about operators in Base

- book/classes/README.md
> Fix some issues with Classes chapter

- book/compiler-backend/README.md
- book/concurrent-programming/README.md
- book/error-handling/README.md
- book/guided-tour/README.md
- book/lists-and-patterns/README.md
- book/parsing-with-ocamllex-and-menhir/README.md
- book/variables-and-functions/README.md
- book/variants/README.md
> switched a bunch of statements to expressions

- bin/pandoc-rwo/pandoc_rwo.ml
- book/compiler-backend/README.md
- book/compiler-frontend/README.md
- book/concurrent-programming/README.md
- book/error-handling/README.md
- book/files-modules-and-programs/README.md
- book/first-class-modules/README.md
- book/foreign-function-interface/README.md
- book/functors/README.md
- book/gadts/README.md
- book/garbage-collector/README.md
- book/guided-tour/README.md
- book/imperative-programming/README.md
- book/json/README.md
- book/lists-and-patterns/README.md
- book/maps-and-hashtables/README.md
- book/objects/README.md
- book/parsing-with-ocamllex-and-menhir/README.md
- book/platform/README.md
- book/runtime-memory-layout/README.md
- book/variables-and-functions/README.md
- book/variants/README.md
- static-wip/dune
- static/dune
converts to hyperref links for xelatex to use
fixes #3463
> fix internal pdf xrefs with a custom pandoc pass

- book/concurrent-programming/README.md
> reword text of explanation of try/with in concurrent programming chapter.

- book/platform/README.md
I just did some reformatting of the chapter so it's a bit easier to edit going forward.
> Whitespace changes to platform chapter

- book/prologue/README.md
> Small fixes

- book/gadts/README.md
- book/toc.scm
put the GADT chapter earlier, make a forward-reference to functors in the one place they show up
> Put GADTs before Functors.

- book/gadts/README.md
> Small GADT tweaks

- bin/pandoc-rwo/pandoc_rwo.ml
- book/classes/README.md
- book/data-serialization/README.md
- book/garbage-collector/README.md
- book/imperative-programming/README.md
- book/objects/README.md
- book/parsing-with-ocamllex-and-menhir/README.md
fixes #3154
also fixes a layout issue in Data Serialisation
> add authorship per chapter

- book/variables-and-functions/README.md
> Close #3319

- book/guided-tour/README.md
Did a paper read of the PDF, and pushed some small changes in response. Notably, added some \noindent markers to avoid indentation in paragraphs that were after code blocks.
> Cleanup to guided tour

- book/compiler-frontend/README.md
- book/concurrent-programming/README.md
- book/first-class-modules/README.md
- book/maps-and-hashtables/README.md
Followup to #3556, the previous one missed out on some references (because I've been fixing these by hand).
Will switch it to ready to review once I have caught up on all.
> Add more double-semicolons

- book/guided-tour/README.md
- book/lists-and-patterns/README.md
A number of fixes:
- lots of noindent
- fixed some examples, made them line up better between guided tour and this chapter. Required some adjustments to that chapter too.
- re-inserted a "note" that had been demoted. Now it doesn't fit, but at least it's obviously wrong.
- Some small language changes.
> Review of lists-and-patterns

- book/cup-template.tex
> use Chapter x.y.z consistently in the pdf

- book/gadts/dune
- book/parsing-with-ocamllex-and-menhir/examples/correct/parsing-test/.rwo-example
- book/parsing-with-ocamllex-and-menhir/examples/dune.inc
- book/testing/examples/correct/bigger_quickcheck_test/.rwo-example
- book/testing/examples/correct/bigger_quickcheck_test_with_ppx/.rwo-example
- book/testing/examples/dune.inc
This fixes the issue with menhir (#3541) and some errors with mdx missing dependencies.
> Add missing dependencies

- book/functors/README.md
- book/gadts/README.md
Final reads. This is mostly some \noindents, but some small other changes:
- Small rewordings
- Fixed some places where Core.Sexpable should have been Sexpable.S
- Removed some stale comments from the code
- Modified some index entries
> GADT and Functor chapter

- book/classes/README.md
- book/first-class-modules/README.md
- book/first-class-modules/examples/correct/query_handler_loader/query_handler_loader.ml
- book/objects/README.md
Mostly very small changes. Almost done with part 1!
> Update to fcm, objects, classes

- book/lists-and-patterns/README.md
> tweak a code example in lists-and-patterns

- book/concurrent-programming/examples/correct/better_echo/.ocamlformat
- book/concurrent-programming/examples/correct/echo/.ocamlformat
- book/concurrent-programming/examples/correct/native_code_log_delays/.ocamlformat
- book/concurrent-programming/examples/correct/search/.ocamlformat
- book/concurrent-programming/examples/correct/search_out_of_order/.ocamlformat
- book/concurrent-programming/examples/correct/search_with_configurable_server/.ocamlformat
- book/concurrent-programming/examples/correct/search_with_error_handling/.ocamlformat
- book/concurrent-programming/examples/correct/search_with_timeout/.ocamlformat
- book/concurrent-programming/examples/correct/search_with_timeout_no_leak/.ocamlformat
- book/concurrent-programming/examples/correct/search_with_timeout_no_leak_simple/.ocamlformat
- book/concurrent-programming/examples/ocamlformat
These were left out of the previous Async review.
> added files

- book/parsing-with-ocamllex-and-menhir/README.md
- book/parsing-with-ocamllex-and-menhir/examples/parsing/json.ml
Very minor. Mostly just deleted some code from the text that seemed unnecessary the flow.
> Review the parsing chapter.

- book/runtime-memory-layout/README.md
Very minor. Just some tweaks, and one substantive question for @avsm.
> Review memory representation

- book/lists-and-patterns/README.md
- book/prologue/README.md
> resolves #3598

- book/command-line-parsing/README.md
- book/compiler-backend/README.md
- book/compiler-frontend/README.md
- book/compiler-frontend/examples/front-end/doc.ml
- book/concurrent-programming/README.md
- book/data-serialization/README.md
- book/error-handling/README.md
- book/files-modules-and-programs/README.md
- book/first-class-modules/README.md
- book/foreign-function-interface/README.md
- book/functors/README.md
- book/gadts/README.md
- book/garbage-collector/README.md
- book/guided-tour/README.md
- book/imperative-programming/README.md
- book/json/README.md
- book/lists-and-patterns/README.md
- book/maps-and-hashtables/README.md
- book/objects/README.md
- book/parsing-with-ocamllex-and-menhir/README.md
- book/platform/README.md
- book/prologue/README.md
- book/runtime-memory-layout/README.md
- book/testing/README.md
- book/variables-and-functions/README.md
- book/variants/README.md
End result of cutting-and-pasting into Google docs and walking through flagged issues. Found a good number of small fixes!
> Spellcheck and grammar check

- book/foreign-function-interface/README.md
I used this around a decade ago with xapian/ocaml, but not
since then!
> ffi: remove swig recommendation

- book/guided-tour/README.md
needed so it works with dune 3.0 + as well
fixes #3617
> create a dune-project file in the guided tour

- book/lists-and-patterns/README.md
> Fixes the small inconsistency noted in #3629

- book/classes/README.md
- book/command-line-parsing/README.md
- book/compiler-backend/README.md
- book/compiler-frontend/README.md
- book/concurrent-programming/README.md
- book/files-modules-and-programs/README.md
- book/first-class-modules/README.md
- book/foreign-function-interface/README.md
- book/gadts/README.md
- book/garbage-collector/README.md
- book/guided-tour/README.md
- book/imperative-programming/README.md
- book/lists-and-patterns/README.md
- book/maps-and-hashtables/README.md
- book/objects/README.md
- book/parsing-with-ocamllex-and-menhir/README.md
- book/part-language-concepts.md
- book/part-tools-and-techniques.md
- book/platform/README.md
- book/testing/README.md
- book/variables-and-functions/README.md
- book/variants/README.md
Mostly capitalization of TOC items, and fixing some index items. But I also transcribed the remaining proofreading notes as TODOs in the text. These are mostly Latex issues that I would leave to you, @avsm, if you don't mind!
> Apply proofreading from OUP

- book/install.html
More simplifications, fixed some internal links.
> Update installation instructions

- book/install.html
> Fix duplication

- book/garbage-collector/README.md
> fix typo in index.
